---
- name: Install Nginx on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Check if python3-apt is installed
      raw: dpkg -l | grep python3-apt
      register: python3_apt_check
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Install python3-apt package if missing
      become: true
      apt:
        name: python3-apt
        state: present
      when: python3_apt_check.rc != 0

    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install Nginx
      become: true
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled
      become: true
      service:
        name: nginx
        state: started
        enabled: yes
